### PR TITLE
Added possibility to use an ip address range to force windows auth

### PR DESCRIPTION
**Pull request by retostadelmann**
Check done using https://www.nuget.org/packages/IPAddressRange/

### CODE REVIEW

**Comment by Yvand** [comment]
Thank you for your contribution! I will take a look and give you a feedback soon

**Comment by Yvand** [comment]
@retostadelmann I did some tests and it looks all good.
I just updated the PR to include IPAddressRange.dll in the wsp package, as it needs to be deployed to the GAC of the SharePoint servers.
I feel a little bit sad about adding this 3rd party assembly to the project as I wanted it to remain as simple as possible, but I understand the benefit of using it.
I will do a few more tests but I will probably merge soon.

**Comment by Yvand** [comment]
CI failed because it is missing a task to restore NuGet packages (there were none before).
I'll fix it and publish a new release as soon as I can

**Comment by Yvand** [comment]
I just published release https://github.com/Yvand/SPBypassLoginPage/releases/tag/2021.08.12.1
@retostadelmann can you give it a try and confirm everything is working as expected?

**Comment by retostadelmann** [comment]
@Yvand Yes we will test this ASAP and get back to you.

**Comment by retostadelmann** [comment]
@Yvand It seems to work fine on our end, thank you for your work!

**Pull request merged**
